<?php

namespace App\Http\Controllers;

use App\Services\RecipeImageService;

/**
 *
 */
class RecipeImageController extends Controller
{

    /**
     * @param RecipeImageService $recipeStepService
     */
    public function __construct(RecipeImageService $recipeStepService)
    {
        parent::setService($recipeStepService);
    }


    public function get($id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }

}
